on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     
     - name: Setup PHP
       uses: shivammathur/setup-php@v2

     - name: Configure aws credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

     - name: Deploy to AWS CodeDeploy
       run: |
        aws deploy create-deployment \
            --application-name ${{secrets.AWS_CODEDEPLOY_APPLICATION}} \
            --deployment-group-name ${{secrets.AWS_CODEDEPLOY_DEPLOYMENT_GROUP}} \
            --description ${GITHUB_SHA} \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --ignore-application-stop-failures